/**:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_acceleration: false
    publish_tf: true
    map_frame: map
    odom_frame: husky1_odom
    base_link_frame: husky1_base_link
    world_frame: husky1_odom
    odom0: odometry
    odom0_config:
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    imu0: imu
    imu0_config:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
