#!/usr/bin/env python3
"""Generate worlds/showcase_forest.sdf from worlds/dense_forest.sdf.

A version of the dense forest for the client demo, where the drone can see
every tree from above:

* oaks are thinned (by name, so the result is always the same) so no two
  are closer than OAK_SEP, which keeps each oak crown separable in the
  canopy height model;
* every pine keeps its name and yaw, but a pine closer than PINE_CLEAR to an
  oak is moved to open ground (at least PINE_CLEAR from every oak and
  PINE_SEP from every other pine). In dense_forest the pines stand 4-6 m
  from oaks, under the oak canopy, where a sensor looking down cannot
  separate them. Pines that do not fit anywhere are dropped.

dense_forest.sdf is not changed; it stays the stress test.

    python3 scripts/make_showcase_world.py            # writes worlds/showcase_forest.sdf
"""

import math
import re
from pathlib import Path

OAK_SEP = 7.0       # m between kept oaks
PINE_CLEAR = 7.0    # m from a pine to every oak (oak crowns reach about 7 m)
PINE_SEP = 3.5      # m between pines (pine crown radius about 1.6 m)
EXTENT = 34.0       # keep trees within +-EXTENT m
GRID = 0.5          # candidate spacing for relocated pines (m)

HERE = Path(__file__).resolve().parents[1] / 'worlds'
SRC = HERE / 'dense_forest.sdf'
DST = HERE / 'showcase_forest.sdf'

TREE_RE = re.compile(
    r'\s*<include>\s*<uri>(?P<uri>[^<]*tree[^<]*)</uri>\s*'
    r'<name>(?P<name>[^<]+)</name>\s*'
    r'<pose>(?P<x>\S+) (?P<y>\S+) \S+ \S+ \S+ (?P<yaw>\S+)</pose>\s*</include>',
    re.IGNORECASE)


def _far(p, others, dist):
    return all(math.hypot(p[0] - o[0], p[1] - o[1]) >= dist for o in others)


def main():
    text = SRC.read_text()
    trees = [dict(m.groupdict(), x=float(m['x']), y=float(m['y']))
             for m in TREE_RE.finditer(text)]
    oaks = sorted((t for t in trees if t['name'].startswith('oak')),
                  key=lambda t: int(t['name'].split('_')[1]))
    pines = sorted((t for t in trees if t['name'].startswith('pine')),
                   key=lambda t: int(t['name'].split('_')[1]))

    kept_oaks = []
    for t in oaks:
        if abs(t['x']) <= EXTENT and abs(t['y']) <= EXTENT and \
                _far((t['x'], t['y']), [(o['x'], o['y']) for o in kept_oaks], OAK_SEP):
            kept_oaks.append(t)
    oak_xy = [(o['x'], o['y']) for o in kept_oaks]

    # Open-ground candidate cells, visited in a fixed shuffled order so the
    # moved pines spread over the whole map instead of filling rows.
    n = int(2 * EXTENT / GRID) + 1
    cells = [(-EXTENT + i * GRID, -EXTENT + j * GRID)
             for i in range(n) for j in range(n)]
    cells = [c for c in cells if _far(c, oak_xy, PINE_CLEAR)]
    cells.sort(key=lambda c: ((int(c[0] * 7919 + c[1] * 104729)) * 2654435761) % 2**32)

    placed, moved, kept_in_place, dropped = [], 0, 0, 0
    for t in pines:                       # pines already clear stay put
        p = (t['x'], t['y'])
        if abs(p[0]) <= EXTENT and abs(p[1]) <= EXTENT and \
                _far(p, oak_xy, PINE_CLEAR) and _far(p, [q[:2] for q in placed], PINE_SEP):
            placed.append((p[0], p[1], t))
            kept_in_place += 1
    ci = 0
    for t in pines:                       # the rest move to open ground
        if any(q[2] is t for q in placed):
            continue
        while ci < len(cells) and not _far(cells[ci], [q[:2] for q in placed], PINE_SEP):
            ci += 1
        if ci >= len(cells):
            dropped += 1
            continue
        placed.append((cells[ci][0], cells[ci][1], t))
        moved += 1
        ci += 1

    def include(uri, name, x, y, yaw):
        return (f'    <include>\n      <uri>{uri}</uri>\n      <name>{name}</name>\n'
                f'      <pose>{x:.1f} {y:.1f} 0 0 0 {yaw}</pose>\n    </include>')

    body = [include(o['uri'], o['name'], o['x'], o['y'], o['yaw']) for o in kept_oaks]
    body += [include(t['uri'], t['name'], x, y, t['yaw']) for x, y, t in placed]

    first = TREE_RE.search(text)
    last_end = list(TREE_RE.finditer(text))[-1].end()
    header = text[:first.start()].replace('<world name="dense_forest">',
                                          '<world name="showcase_forest">')
    note = ('\n    <!-- Generated by scripts/make_showcase_world.py from dense_forest.sdf:\n'
            f'         {len(kept_oaks)} oaks (>= {OAK_SEP} m apart), {len(placed)} pines '
            f'(>= {PINE_CLEAR} m from every oak, >= {PINE_SEP} m apart;\n'
            f'         {kept_in_place} in place, {moved} moved, {dropped} dropped). -->\n')
    DST.write_text(header + note + '\n'.join(body) + text[last_end:])
    print(f'{DST.name}: {len(kept_oaks)} oaks, {len(placed)} pines '
          f'({kept_in_place} in place, {moved} moved, {dropped} dropped)')


if __name__ == '__main__':
    main()
